# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP app to Azure Web App - pnjh2hrizky

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore NuGet packages
        run: nuget restore

      - name: Publish to folder
        run: msbuild /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="\published\"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: '/published/**'

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '18.x'  # Versi Node.js LTS terbaru
          cache: 'npm'          # Menggunakan cache untuk npm dependencies

      # Langkah-langkah lainnya, misalnya install dependensi dan build
      - name: Install dependencies
        run: npm ci  # npm ci lebih cepat dan konsisten daripada npm install di lingkungan CI/CD

      - name: Run build
        run: npm run build
          

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ASP-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_300801BB5677433AA0A8D46DD3D62EA5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FA38DB0B8CCB4D7290E07C2F2377F900 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B2685A9183524A49AC79FC5FB516C5C8 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pnjh2hrizky'
          slot-name: 'Production'
          package: .
